### ISSUE TITLE
Is shift open to being more flexible on foreignID types?

### ISSUE THREAD

**Issue by rickkln** [luno/shift#4]
We are busy implementing `shift` and `reflex` at [Nile](https://github.com/nileag). We make extensive use of [ksuids](https://github.com/segmentio/ksuid) which have string and binary representations. Shift expects the `foreignID`s in the `eventInserter` interface to be `int64`s.

If we worked on a PR to make shift more flexible in terms of the types of foreignIDs it can accept would this be accepted here? Would like to check in before starting such work.

```go
// eventInserter inserts reflex events into a sql DB table.
// It is implemented by rsql.EventsTableInt.
type eventInserter interface {
	InsertWithMetadata(ctx context.Context, tx *sql.Tx, foreignID int64,
		typ reflex.EventType, metadata []byte) (rsql.NotifyFunc, error)
}
```

**Comment by rickkln** [comment]
fyi @pedreviljoen

**Comment by pedreviljoen** [comment]
@rickkln 
Thanks Rick, yes that is the underlying `interface` we need to work with 👍🏻

**Comment by moolmanruan** [comment]
@rickkln, we've added support string IDs.

**Comment by rickkln** [comment]
Brilliant! @moolmanruan didn't even notice the draft coming through, you guys are super fast 👏 This will help us out a lot! Excited to use Reflex and Shift a lot more now.

![fanks](https://media.giphy.com/media/6mBnSxxldVZYusjhtP/giphy.gif)
